# Generated by Django 3.0.4 on 2020-03-30 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='caption',
            new_name='description',
        ),
    ]
