# Generated by Django 3.0.4 on 2020-03-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_auto_20200315_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
