# Generated by Django 3.0.4 on 2020-03-31 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0004_tguser_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
