# Generated by Django 3.0.4 on 2020-04-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0005_auto_20200331_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
